### PR TITLE
Use grafana 6.0.2 by default

### PR DESCRIPTION
**Pull request by suckatrash**
Update to the latest packaging by Grafana Labs

### CODE REVIEW

**Comment by jarretlavallee** [comment]
LGTM @suckatrash is there anything else needed with this PR or are you good to merge it?

**Comment by suckatrash** [comment]
This is sort of blocked because in Grafana 6 you'll be prompted to change the password from the default when you log in for the first time. That means that a user might go with a default configuration, log in, change the password and then end up with failing puppet runs.  

We don't have a way to manage the password, so until we do this is blocked.

**Comment by jarretlavallee** [comment]
thanks @suckatrash

**Comment by jarretlavallee** [comment]
I looked into this a bit more @suckatrash and I think it is possible. Apparently, if we set https://grafana.com/docs/installation/configuration/#admin-password to anything before the first login, it will not prompt for a password change.

It looks like we can specify that in `grafana::cfg` like https://github.com/voxpupuli/puppet-grafana#cfg

Doing a quick test in https://github.com/puppetlabs/puppet_metrics_dashboard/blob/master/manifests/grafana.pp#L25-L31, even with the default as `admin` setting the following did not prompt me for a password change.

~~~
    $grafana_cfg = {
      server    => {
        http_port => $puppet_metrics_dashboard::grafana_http_port,
      },
      security => {
        admin_password => $puppet_metrics_dashboard::grafana_password,
      }
    }
  }
~~~

I am not sure how I feel about leaving a password in plain text on the file system, but since this should only be the default password, we can set it to `admin` and it will not need to be updated as the password changes.

**Pull request closed without merging**
