### PR TITLE
readme changes for sup-2378

### PR DESCRIPTION
**Pull request by MartyEwings**

### CODE REVIEW

**Review by pgrant87 — APPROVED** [review]
changes look good!

**Review by elainemccloskey — APPROVED** [review]
Looks good

**Comment by MartyEwings** [comment]
@jarretlavallee @suckatrash looks like this is failing because puppet5 is not an option in litmus or bolt anylonger. does anyone have admin access to merge anyway?

**Review by gavindidrichsen — APPROVED** [review]
Looks good to me!

**Comment by jarretlavallee** [comment]
The `Manual Local Testing` section needs to be migrated somewhere else before this can be merged. That section has the information around how to run the local viewer.

**Review by gavindidrichsen — APPROVED** [review]
LGTM

**Review by jarretlavallee — CHANGES_REQUESTED** [review]
Before merging, the local viewer docs need to be migrated out of the contributing doc into the readme.

**Pull request closed without merging**
