### PR TITLE
(SUP-2551) Refactor Master Profile to remove harmful terminology

### PR DESCRIPTION
**Pull request by MartyEwings**

### CODE REVIEW

**Comment by jarretlavallee** [comment]
@sandrajiang Please sign the CLA and rebase this PR.

https://cla-assistant.io/puppetlabs/puppet_metrics_dashboard?pullRequest=168

**Review by sandrajiang — COMMENTED** [review]
Gone through the changes and they look good!

Thanks

**Comment by MartyEwings** [comment]
@m0dular could you rebase this on main to pick up the new test environment so we can push this in

**Comment by MartyEwings** [comment]
Closing as this is being handled by part of the uplift project

**Pull request closed without merging**
