### PR TITLE
adds puppet7 testing / support

### PR DESCRIPTION
**Pull request by suckatrash**

### CODE REVIEW

**Comment by jarretlavallee** [comment]
It looks like Debian 8 went EOL and won't install Puppet 7. We can consider dropping it as a platform and adding in Debian 10 for the Debian testing. That would be a simple swap in provision.yaml

**Comment by suckatrash** [comment]
What I ended up doing was keeping some of the older platforms around for puppet5 / legacy testing.  Think that's ok?

**Comment by jarretlavallee** [comment]
That's a great idea. It just needs to be added into the `.sync.yml` or it will be lost on the next `pdk update`. With the changes, we would be looking for an added spec test and `litmus\complex\collection`. That doesn't allow for removing the defaults

Maybe something like the following? It should knockout the default collection of `puppet5` to allow it to use legacy testing. It may need some changes if we need to do the same for `puppet6`.

```
.travis.yml:
  branches:
    - /.*/
  use_litmus: true
  litmus:
    puppet_collection:
      - ---puppet5
      - puppet6
      - puppet7
    complex:
      - collection:
          puppet_collection:
            - puppet5
          provision_list:
            - travis_deb_legacy
            - travis_el
  includes:
    - env: PUPPET_GEM_VERSION="~> 7.0" CHECK=parallel_spec
      rvm: 2.7.2
      stage: spec
```

**Comment by jarretlavallee** [comment]
I ran a `pdk update` and see a few changes. The only real change is the `rvm` version for the Puppet7 litmus tests. Since this is the acceptance test that installs puppet7 in the container and the ruby version is only used for litmus, I think that should be fine. Would you mind doing a `pdk update` and we will merge this in?

```
diff --git a/.travis.yml b/.travis.yml
index 7b01bfd..4efb83b 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -33,7 +33,7 @@ jobs:
       - "bundle exec rake 'litmus:install_agent[puppet5]'"
       - "bundle exec rake litmus:install_module"
       bundler_args:
-      env: PLATFORMS=travis_deb_puppet5
+      env: PLATFORMS=travis_deb_legacy_puppet5
       rvm: 2.5.7
       script: ["travis_wait 45 bundle exec rake litmus:acceptance:parallel"]
       services: docker
@@ -78,7 +78,7 @@ jobs:
       - "bundle exec rake litmus:install_module"
       bundler_args:
       env: PLATFORMS=travis_deb_puppet7
-      rvm: 2.7.2
+      rvm: 2.5.7
       script: ["travis_wait 45 bundle exec rake litmus:acceptance:parallel"]
       services: docker
       stage: acceptance
@@ -89,7 +89,7 @@ jobs:
       - "bundle exec rake litmus:install_module"
       bundler_args:
       env: PLATFORMS=travis_el_puppet7
-      rvm: 2.7.2
+      rvm: 2.5.7
       script: ["travis_wait 45 bundle exec rake litmus:acceptance:parallel"]
       services: docker
       stage: acceptance
```

**Review by jarretlavallee — APPROVED** [review]
LGTM

**Pull request merged**
