### PR TITLE
Enable remote PuppetDB collection in 2019.8.5+

### PR DESCRIPTION
**Pull request by jarretlavallee**
This PR enables remote PuppetDB collection by default when using PE 2019.8.5+. It does this by adding a new PuppetDB version fact and using that in a PuppetDB query for the PuppetDB nodes. The PR includes some clean up such as the following. 

* Consolidate all facts into a `puppet_metrics_dashboard` hash
* Rename a function to better align with its current purpose

### CODE REVIEW

**Review by suckatrash — CHANGES_REQUESTED** [review]
It looks like the function `puppet_metrics_dashboard::puppetdb_no_remote_metrics` was removed but I don't see that a file for `puppet_metrics_dashboard::puppetdb_v2_metrics` was added?

**Comment by jarretlavallee** [comment]
Good call. I just pushed up a commit with it in there.

**Review by suckatrash — APPROVED** [review]

**Comment by jarretlavallee** [comment]
I was not expecting that failure. I can fix it by adding `trusted_facts` to https://github.com/puppetlabs/puppet_metrics_dashboard/blob/master/spec/classes/dashboards/telegraf_spec.rb#L9 but I am not sure how it was working before.  I didn't intentionally change how the `master_list` is populated and don't see how it would have. Either way, it works on my machine and I will push a change to the spec to add the `trusted_facts`. Let me know if you see something I don't.

**Comment by jarretlavallee** [comment]
Alright, that last commit should fix some of the last issues. Hopefully, the acceptance tests are green now.

**Review by suckatrash — APPROVED** [review]

**Pull request merged**
