### PR TITLE
SUP-2428-ci-migration

### PR DESCRIPTION
**Pull request by MartyEwings**
SUP-2428-ci-migration using Puppet for Acceptance tests

### CODE REVIEW

**Comment by MartyEwings** [comment]
@m0dular how did you get a workflow not already in the puppetlabs repo to run? the acceptance tests are not running here, id like to make sure they work before merging over there

**Comment by MartyEwings** [comment]
Closing to trigger workflows

**Comment by MartyEwings** [comment]
reopen to trigger workflow

**Comment by MartyEwings** [comment]
@m0dular Bingo, can i get a review and merge?

**Review by gavindidrichsen — APPROVED** [review]
👍

**Pull request merged**
