### PR TITLE
Update puppetlabs module dependencies

### PR DESCRIPTION
**Pull request by Sharpie**
This commit updates the version ranges of dependencies on the
puppetlabs-stdlib, puppetlabs-inifile, and puppetlabs-apt modules
to allow newly released major versions.

### CODE REVIEW

**Comment by genebean** [comment]
@Sharpie - have you run tests with those versions? the `.fixtures` file is pinned to exact tags.

**Comment by jarretlavallee** [comment]
It looks like the major versions in those modules are to drop puppet 4.x support. I updated the `.fixtures.yml` in my environment and ran the beaker tests and they passed along with the spec tests. It would be worth running it in a real environment to validate the functionality. 

@genebean What are your thoughts on updating the version in the `.fixtures.yml`? Should we leave them on the older versions to maintain compatibility or update them to verify newer versions?

**Comment by genebean** [comment]
IMO, .fixtures should pull the current version from the forge at all times as we'd rather it fail in ci than fail when a user uses a current module.

**Comment by Sharpie** [comment]
Hah, yeah. I always miss `.fixtures.yaml` since it's a hidden file :)

Looks like it's already massively out of date with respect to the versions in `metadata.json`. Should we even be pinning versions there? I looked at a few supported modules and their fixtures files don't pin refs and appear to pull directly from the master branch of the dependencies. E.g.:

https://github.com/puppetlabs/puppetlabs-apache/blob/master/.fixtures.yml
https://github.com/puppetlabs/puppetlabs-postgresql/blob/master/.fixtures.yml

**Comment by Sharpie** [comment]
Added a commit that removes the version pins from `.fixtures.yml`.

**Pull request merged**
